services:
  - type: web
    name: KARLA-MD
    env: node
    branch: main
    repo: https://github.com/papaigwe1234/KARLA-MD.git
    buildCommand: npm install
    startCommand: npm start
    plan: free
    autoDeploy: false
    envVars:
      - key: SESSION_ID
        sync: false
      - key: DATABASE_URL
        sync: false
